remote_theme: just-the-docs/just-the-docs

title: Lancet
baseurl: "/" # will need to double check what this should be
url: "https://nygenome.github.io"
permalink: pretty
#search_enabled: true
heading_anchors: true

# Aux links for upper right navigation button
aux_links:
  "Lancet Github Repo":
    - "//github.com/nygenome/Lancet2"
aux_links_new_tab: false

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to Top"

footer_content: "Some footer content"

gh_edit_repository: "https://github.com/nygenome/Lancet2" # the github URL for your repo
gh_edit_branch: "gh-pages" # branch docs are served from
gh_edit_view_mode: "tree"

color_scheme: nil

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   #   envs: all
