context:
  name: lancet2

package:
  name: ${{ name|lower }}
  version: ${{ env.get("LANCET_VERSION", "0.0.0") }}

source:
  # Mount the entire active local tree for rattler build
  path: ..

build:
  number: 0
  string: ${{ env.get("LANCET_BUILD_STRING", "local_0") }}
  script: |
    mkdir build && cd build
    cmake -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DLANCET_BUILD_STATIC=OFF \
      -DLANCET_ENABLE_CLOUD_IO=ON \
      ..
    ninja install -v

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake >=3.25
    - ninja
  host:
    - libcurl
    - openssl
    - bzip2
    - xz
  run:
    - libcurl
    - openssl
    - bzip2
    - xz

tests:
  - script:
      - Lancet2 --version

about:
  homepage: https://github.com/nygenome/Lancet2
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Lancet2 is an accurate, C++-based variant caller utilizing localized colored de Bruijn graph assembly
