name: filter_lancet2
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.12.1
  - dash=2.15.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - dash_cytoscape=0.2.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - flask=3.0.2
  - fonttools=4.49.0
  - freetype=2.12.1
  - gevent=23.9.0.post1
  - greenlet=3.0.3
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - interpret=0.5.1
  - interpret-core=0.5.1
  - ipykernel=6.29.2
  - ipython=8.22.1
  - itsdangerous=2.1.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - kiwisolver=1.4.5
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.19
  - libebm=0.5.1
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libuv=1.47.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - multiprocess=0.70.16
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numba=0.59.0
  - numpy=1.26.4
  - openjpeg=2.5.1
  - openssl=3.2.1
  - packaging=23.2
  - pandas=2.2.1
  - parso=0.8.3
  - pathos=0.3.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - platformdirs=4.2.0
  - plotly=5.19.0
  - pox=0.3.4
  - ppft=1.7.6.8
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - retrying=1.3.3
  - salib=1.4.8
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.1.1
  - shap=0.42.1
  - six=1.16.0
  - slicer=0.0.7
  - stack_data=0.6.2
  - tenacity=8.2.3
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.1
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zope.event=5.0
  - zope.interface=6.2
  - zstd=1.5.5
  - pip:
      - pysam==0.22.0
