find_package(Git REQUIRED)
set(LANCET2_VERSION_TAG ${PROJECT_VERSION})

execute_process(COMMAND ${GIT_EXECUTABLE} describe --abbrev=0 --tags WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
		OUTPUT_VARIABLE LANCET2_GIT_TAG ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
		OUTPUT_VARIABLE LANCET2_GIT_BRANCH ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short=10 --verify HEAD WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
		OUTPUT_VARIABLE LANCET2_GIT_REVISION ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)

if (NOT LANCET2_GIT_TAG)
	set(LANCET2_GIT_TAG "2.3.0")
endif ()

if (NOT LANCET2_GIT_BRANCH)
	set(LANCET2_GIT_BRANCH "UNKNOWN-HEAD")
endif ()

if (NOT LANCET2_GIT_REVISION)
	set(LANCET2_GIT_REVISION "xxxxxxxxxx")
endif ()

set(LANCET2_VERSION_HEADER "${CMAKE_BINARY_DIR}/generated/lancet_version.h")
configure_file("${CMAKE_SOURCE_DIR}/src/lancet/version.h.inc" ${LANCET2_VERSION_HEADER} @ONLY)
